#############################################################################
# Makefile for building: QFractals
# Generated by qmake (2.01a) (Qt 4.7.0) on: Tue Jun 1 18:14:59 2010
# Project:  QFractals.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile QFractals.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/opt/local/include/ -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		graphics/colorpalette.cpp \
		math/transformation.cpp \
		math/spline.cpp \
		graphics/imagewrapper.cpp \
		graphics/renderedimage.cpp \
		graphics/plottedimage.cpp \
		ui/selectablewidget.cpp \
		settings.cpp \
		ui/mainwindow.cpp \
		graphics/image.cpp \
		fractals/specification.cpp \
		fractals/viewport.cpp \
		fractals/rendering.cpp \
		fractals/mandelbrot.cpp \
		ui/imagecontrolwidget.cpp \
		ui/resizedialog.cpp \
		fractals/pendulum.cpp \
		fractals/plotting.cpp \
		fractals/ifs.cpp \
		math/interpreter.cpp moc_selectablewidget.cpp \
		moc_mainwindow.cpp \
		moc_specification.cpp \
		moc_imagecontrolwidget.cpp \
		moc_resizedialog.cpp
OBJECTS       = main.o \
		colorpalette.o \
		transformation.o \
		spline.o \
		imagewrapper.o \
		renderedimage.o \
		plottedimage.o \
		selectablewidget.o \
		settings.o \
		mainwindow.o \
		image.o \
		specification.o \
		viewport.o \
		rendering.o \
		mandelbrot.o \
		imagecontrolwidget.o \
		resizedialog.o \
		pendulum.o \
		plotting.o \
		ifs.o \
		interpreter.o \
		moc_selectablewidget.o \
		moc_mainwindow.o \
		moc_specification.o \
		moc_imagecontrolwidget.o \
		moc_resizedialog.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		QFractals.pro
QMAKE_TARGET  = QFractals
DESTDIR       = 
TARGET        = QFractals

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QFractals.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile QFractals.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile QFractals.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QFractals1.0.0 || $(MKDIR) .tmp/QFractals1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QFractals1.0.0/ && $(COPY_FILE) --parents graphics/colorpalette.h math/transformation.h math/spline.h graphics/imagewrapper.h graphics/renderedimage.h graphics/plottedimage.h graphics/image.h ui/selectablewidget.h settings.h ui/mainwindow.h fractals/specification.h fractals/viewport.h fractals/rendering.h fractals/mandelbrot.h fractals/plotting.h fractals/ifs.h ui/imagecontrolwidget.h ui/resizedialog.h fractals/pendulum.h math/interpreter.h .tmp/QFractals1.0.0/ && $(COPY_FILE) --parents main.cpp graphics/colorpalette.cpp math/transformation.cpp math/spline.cpp graphics/imagewrapper.cpp graphics/renderedimage.cpp graphics/plottedimage.cpp ui/selectablewidget.cpp settings.cpp ui/mainwindow.cpp graphics/image.cpp fractals/specification.cpp fractals/viewport.cpp fractals/rendering.cpp fractals/mandelbrot.cpp ui/imagecontrolwidget.cpp ui/resizedialog.cpp fractals/pendulum.cpp fractals/plotting.cpp fractals/ifs.cpp math/interpreter.cpp .tmp/QFractals1.0.0/ && (cd `dirname .tmp/QFractals1.0.0` && $(TAR) QFractals1.0.0.tar QFractals1.0.0 && $(COMPRESS) QFractals1.0.0.tar) && $(MOVE) `dirname .tmp/QFractals1.0.0`/QFractals1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QFractals1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_selectablewidget.cpp moc_mainwindow.cpp moc_specification.cpp moc_imagecontrolwidget.cpp moc_resizedialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_selectablewidget.cpp moc_mainwindow.cpp moc_specification.cpp moc_imagecontrolwidget.cpp moc_resizedialog.cpp
moc_selectablewidget.cpp: fractals/specification.h \
		graphics/image.h \
		ui/selectablewidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ui/selectablewidget.h -o moc_selectablewidget.cpp

moc_mainwindow.cpp: fractals/specification.h \
		graphics/image.h \
		ui/imagecontrolwidget.h \
		ui/selectablewidget.h \
		ui/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ui/mainwindow.h -o moc_mainwindow.cpp

moc_specification.cpp: graphics/image.h \
		fractals/specification.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) fractals/specification.h -o moc_specification.cpp

moc_imagecontrolwidget.cpp: ui/selectablewidget.h \
		fractals/specification.h \
		graphics/image.h \
		ui/imagecontrolwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ui/imagecontrolwidget.h -o moc_imagecontrolwidget.cpp

moc_resizedialog.cpp: ui/resizedialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ui/resizedialog.h -o moc_resizedialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp ui/mainwindow.h \
		fractals/specification.h \
		graphics/image.h \
		ui/imagecontrolwidget.h \
		ui/selectablewidget.h \
		math/spline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

colorpalette.o: graphics/colorpalette.cpp graphics/colorpalette.h \
		math/spline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colorpalette.o graphics/colorpalette.cpp

transformation.o: math/transformation.cpp math/transformation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transformation.o math/transformation.cpp

spline.o: math/spline.cpp math/spline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spline.o math/spline.cpp

imagewrapper.o: graphics/imagewrapper.cpp graphics/imagewrapper.h \
		graphics/image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagewrapper.o graphics/imagewrapper.cpp

renderedimage.o: graphics/renderedimage.cpp graphics/renderedimage.h \
		graphics/imagewrapper.h \
		graphics/image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o renderedimage.o graphics/renderedimage.cpp

plottedimage.o: graphics/plottedimage.cpp graphics/plottedimage.h \
		graphics/imagewrapper.h \
		graphics/image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plottedimage.o graphics/plottedimage.cpp

selectablewidget.o: ui/selectablewidget.cpp ui/selectablewidget.h \
		fractals/specification.h \
		graphics/image.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o selectablewidget.o ui/selectablewidget.cpp

settings.o: settings.cpp settings.h \
		ui/selectablewidget.h \
		fractals/specification.h \
		graphics/image.h \
		fractals/mandelbrot.h \
		fractals/rendering.h \
		fractals/viewport.h \
		math/transformation.h \
		graphics/renderedimage.h \
		graphics/imagewrapper.h \
		graphics/colorpalette.h \
		math/spline.h \
		math/interpreter.h \
		fractals/pendulum.h \
		fractals/ifs.h \
		fractals/plotting.h \
		graphics/plottedimage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

mainwindow.o: ui/mainwindow.cpp ui/mainwindow.h \
		fractals/specification.h \
		graphics/image.h \
		ui/imagecontrolwidget.h \
		ui/selectablewidget.h \
		settings.h \
		fractals/mandelbrot.h \
		fractals/rendering.h \
		fractals/viewport.h \
		math/transformation.h \
		graphics/renderedimage.h \
		graphics/imagewrapper.h \
		graphics/colorpalette.h \
		math/spline.h \
		math/interpreter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ui/mainwindow.cpp

image.o: graphics/image.cpp graphics/image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o image.o graphics/image.cpp

specification.o: fractals/specification.cpp fractals/specification.h \
		graphics/image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specification.o fractals/specification.cpp

viewport.o: fractals/viewport.cpp fractals/viewport.h \
		fractals/specification.h \
		graphics/image.h \
		math/transformation.h \
		settings.h \
		ui/selectablewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewport.o fractals/viewport.cpp

rendering.o: fractals/rendering.cpp fractals/rendering.h \
		fractals/viewport.h \
		fractals/specification.h \
		graphics/image.h \
		math/transformation.h \
		graphics/renderedimage.h \
		graphics/imagewrapper.h \
		settings.h \
		ui/selectablewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rendering.o fractals/rendering.cpp

mandelbrot.o: fractals/mandelbrot.cpp fractals/mandelbrot.h \
		fractals/rendering.h \
		fractals/viewport.h \
		fractals/specification.h \
		graphics/image.h \
		math/transformation.h \
		graphics/renderedimage.h \
		graphics/imagewrapper.h \
		graphics/colorpalette.h \
		math/spline.h \
		math/interpreter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mandelbrot.o fractals/mandelbrot.cpp

imagecontrolwidget.o: ui/imagecontrolwidget.cpp ui/imagecontrolwidget.h \
		ui/selectablewidget.h \
		fractals/specification.h \
		graphics/image.h \
		settings.h \
		ui/resizedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagecontrolwidget.o ui/imagecontrolwidget.cpp

resizedialog.o: ui/resizedialog.cpp ui/resizedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resizedialog.o ui/resizedialog.cpp

pendulum.o: fractals/pendulum.cpp fractals/pendulum.h \
		fractals/rendering.h \
		fractals/viewport.h \
		fractals/specification.h \
		graphics/image.h \
		math/transformation.h \
		graphics/renderedimage.h \
		graphics/imagewrapper.h \
		graphics/colorpalette.h \
		math/spline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pendulum.o fractals/pendulum.cpp

plotting.o: fractals/plotting.cpp fractals/plotting.h \
		fractals/viewport.h \
		fractals/specification.h \
		graphics/image.h \
		math/transformation.h \
		graphics/plottedimage.h \
		graphics/imagewrapper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plotting.o fractals/plotting.cpp

ifs.o: fractals/ifs.cpp fractals/ifs.h \
		fractals/plotting.h \
		fractals/viewport.h \
		fractals/specification.h \
		graphics/image.h \
		math/transformation.h \
		graphics/plottedimage.h \
		graphics/imagewrapper.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ifs.o fractals/ifs.cpp

interpreter.o: math/interpreter.cpp math/interpreter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interpreter.o math/interpreter.cpp

moc_selectablewidget.o: moc_selectablewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_selectablewidget.o moc_selectablewidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_specification.o: moc_specification.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_specification.o moc_specification.cpp

moc_imagecontrolwidget.o: moc_imagecontrolwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imagecontrolwidget.o moc_imagecontrolwidget.cpp

moc_resizedialog.o: moc_resizedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_resizedialog.o moc_resizedialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

