#############################################################################
# Makefile for building: QFractals.app/Contents/MacOS/QFractals
# Generated by qmake (2.01a) (Qt 4.6.1) on: Sat Mar 13 16:30:30 2010
# Project:  QFractals.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile QFractals.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -gdwarf-2 -arch i386 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch i386 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Qt4.6/mkspecs/macx-g++ -I. -I/Library/Frameworks/QtCore.framework/Versions/4/Headers -I/usr/include/QtCore -I/Library/Frameworks/QtGui.framework/Versions/4/Headers -I/usr/include/QtGui -I/usr/include -I. -F/Library/Frameworks
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch i386
LIBS          = $(SUBLIBS) -F/Library/Frameworks -L/Library/Frameworks -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		graphics/colorpalette.cpp \
		math/transformation.cpp \
		math/spline.cpp \
		graphics/imagewrapper.cpp \
		graphics/renderedimage.cpp \
		graphics/plottedimage.cpp \
		ui/selectablewidget.cpp \
		settings.cpp \
		ui/mainwindow.cpp \
		math/complex.cpp \
		graphics/image.cpp \
		fractals/specification.cpp \
		fractals/viewport.cpp \
		fractals/rendering.cpp \
		fractals/mandelbrot.cpp \
		ui/imagecontrolwidget.cpp \
		ui/resizedialog.cpp moc_selectablewidget.cpp \
		moc_mainwindow.cpp \
		moc_specification.cpp \
		moc_imagecontrolwidget.cpp \
		moc_resizedialog.cpp
OBJECTS       = main.o \
		colorpalette.o \
		transformation.o \
		spline.o \
		imagewrapper.o \
		renderedimage.o \
		plottedimage.o \
		selectablewidget.o \
		settings.o \
		mainwindow.o \
		complex.o \
		image.o \
		specification.o \
		viewport.o \
		rendering.o \
		mandelbrot.o \
		imagecontrolwidget.o \
		resizedialog.o \
		moc_selectablewidget.o \
		moc_mainwindow.o \
		moc_specification.o \
		moc_imagecontrolwidget.o \
		moc_resizedialog.o
DIST          = /usr/local/Qt4.6/mkspecs/common/unix.conf \
		/usr/local/Qt4.6/mkspecs/common/mac.conf \
		/usr/local/Qt4.6/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.6/mkspecs/qconfig.pri \
		/usr/local/Qt4.6/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.6/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.6/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.6/mkspecs/features/debug.prf \
		/usr/local/Qt4.6/mkspecs/features/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.6/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.6/mkspecs/features/qt.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.6/mkspecs/features/moc.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.6/mkspecs/features/resources.prf \
		/usr/local/Qt4.6/mkspecs/features/uic.prf \
		/usr/local/Qt4.6/mkspecs/features/yacc.prf \
		/usr/local/Qt4.6/mkspecs/features/lex.prf \
		/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf \
		QFractals.pro
QMAKE_TARGET  = QFractals
DESTDIR       = 
TARGET        = QFractals.app/Contents/MacOS/QFractals

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		i386 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile QFractals.app/Contents/PkgInfo QFractals.app/Contents/Resources/empty.lproj QFractals.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) QFractals.app/Contents/MacOS/ || $(MKDIR) QFractals.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QFractals.pro  /usr/local/Qt4.6/mkspecs/macx-g++/qmake.conf /usr/local/Qt4.6/mkspecs/common/unix.conf \
		/usr/local/Qt4.6/mkspecs/common/mac.conf \
		/usr/local/Qt4.6/mkspecs/common/mac-g++.conf \
		/usr/local/Qt4.6/mkspecs/qconfig.pri \
		/usr/local/Qt4.6/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.6/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.6/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.6/mkspecs/features/debug.prf \
		/usr/local/Qt4.6/mkspecs/features/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/x86.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.6/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.6/mkspecs/features/qt.prf \
		/usr/local/Qt4.6/mkspecs/features/unix/thread.prf \
		/usr/local/Qt4.6/mkspecs/features/moc.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.6/mkspecs/features/resources.prf \
		/usr/local/Qt4.6/mkspecs/features/uic.prf \
		/usr/local/Qt4.6/mkspecs/features/yacc.prf \
		/usr/local/Qt4.6/mkspecs/features/lex.prf \
		/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf \
		/Library/Frameworks/QtGui.framework/QtGui.prl \
		/Library/Frameworks/QtCore.framework/QtCore.prl
	$(QMAKE) -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile QFractals.pro
/usr/local/Qt4.6/mkspecs/common/unix.conf:
/usr/local/Qt4.6/mkspecs/common/mac.conf:
/usr/local/Qt4.6/mkspecs/common/mac-g++.conf:
/usr/local/Qt4.6/mkspecs/qconfig.pri:
/usr/local/Qt4.6/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.6/mkspecs/features/qt_config.prf:
/usr/local/Qt4.6/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.6/mkspecs/features/default_pre.prf:
/usr/local/Qt4.6/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.6/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.6/mkspecs/features/debug.prf:
/usr/local/Qt4.6/mkspecs/features/default_post.prf:
/usr/local/Qt4.6/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.6/mkspecs/features/mac/x86.prf:
/usr/local/Qt4.6/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.6/mkspecs/features/warn_on.prf:
/usr/local/Qt4.6/mkspecs/features/qt.prf:
/usr/local/Qt4.6/mkspecs/features/unix/thread.prf:
/usr/local/Qt4.6/mkspecs/features/moc.prf:
/usr/local/Qt4.6/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.6/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.6/mkspecs/features/resources.prf:
/usr/local/Qt4.6/mkspecs/features/uic.prf:
/usr/local/Qt4.6/mkspecs/features/yacc.prf:
/usr/local/Qt4.6/mkspecs/features/lex.prf:
/usr/local/Qt4.6/mkspecs/features/include_source_dir.prf:
/Library/Frameworks/QtGui.framework/QtGui.prl:
/Library/Frameworks/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.6/mkspecs/macx-g++ -macx -o Makefile QFractals.pro

QFractals.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) QFractals.app/Contents || $(MKDIR) QFractals.app/Contents 
	@$(DEL_FILE) QFractals.app/Contents/PkgInfo
	@echo "APPL????" >QFractals.app/Contents/PkgInfo
QFractals.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) QFractals.app/Contents/Resources || $(MKDIR) QFractals.app/Contents/Resources 
	@touch QFractals.app/Contents/Resources/empty.lproj
	
QFractals.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) QFractals.app/Contents || $(MKDIR) QFractals.app/Contents 
	@$(DEL_FILE) QFractals.app/Contents/Info.plist
	@sed -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,QFractals,g" -e "s,@TYPEINFO@,????,g" /usr/local/Qt4.6/mkspecs/macx-g++/Info.plist.app >QFractals.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/QFractals1.0.0 || $(MKDIR) .tmp/QFractals1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QFractals1.0.0/ && $(COPY_FILE) --parents graphics/colorpalette.h math/transformation.h math/spline.h graphics/imagewrapper.h graphics/renderedimage.h graphics/plottedimage.h graphics/image.h ui/selectablewidget.h settings.h ui/mainwindow.h math/complex.h fractals/specification.h fractals/viewport.h fractals/rendering.h fractals/mandelbrot.h ui/imagecontrolwidget.h ui/resizedialog.h .tmp/QFractals1.0.0/ && $(COPY_FILE) --parents main.cpp graphics/colorpalette.cpp math/transformation.cpp math/spline.cpp graphics/imagewrapper.cpp graphics/renderedimage.cpp graphics/plottedimage.cpp ui/selectablewidget.cpp settings.cpp ui/mainwindow.cpp math/complex.cpp graphics/image.cpp fractals/specification.cpp fractals/viewport.cpp fractals/rendering.cpp fractals/mandelbrot.cpp ui/imagecontrolwidget.cpp ui/resizedialog.cpp .tmp/QFractals1.0.0/ && (cd `dirname .tmp/QFractals1.0.0` && $(TAR) QFractals1.0.0.tar QFractals1.0.0 && $(COMPRESS) QFractals1.0.0.tar) && $(MOVE) `dirname .tmp/QFractals1.0.0`/QFractals1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QFractals1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r QFractals.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_selectablewidget.cpp moc_mainwindow.cpp moc_specification.cpp moc_imagecontrolwidget.cpp moc_resizedialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_selectablewidget.cpp moc_mainwindow.cpp moc_specification.cpp moc_imagecontrolwidget.cpp moc_resizedialog.cpp
moc_selectablewidget.cpp: fractals/specification.h \
		graphics/image.h \
		ui/selectablewidget.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ui/selectablewidget.h -o moc_selectablewidget.cpp

moc_mainwindow.cpp: fractals/specification.h \
		graphics/image.h \
		ui/imagecontrolwidget.h \
		ui/selectablewidget.h \
		ui/mainwindow.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ui/mainwindow.h -o moc_mainwindow.cpp

moc_specification.cpp: graphics/image.h \
		fractals/specification.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ fractals/specification.h -o moc_specification.cpp

moc_imagecontrolwidget.cpp: ui/selectablewidget.h \
		fractals/specification.h \
		graphics/image.h \
		ui/imagecontrolwidget.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ui/imagecontrolwidget.h -o moc_imagecontrolwidget.cpp

moc_resizedialog.cpp: ui/resizedialog.h
	/Developer/Tools/Qt/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ui/resizedialog.h -o moc_resizedialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp ui/mainwindow.h \
		fractals/specification.h \
		graphics/image.h \
		ui/imagecontrolwidget.h \
		ui/selectablewidget.h \
		math/spline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

colorpalette.o: graphics/colorpalette.cpp graphics/colorpalette.h \
		math/spline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o colorpalette.o graphics/colorpalette.cpp

transformation.o: math/transformation.cpp math/transformation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transformation.o math/transformation.cpp

spline.o: math/spline.cpp math/spline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spline.o math/spline.cpp

imagewrapper.o: graphics/imagewrapper.cpp graphics/imagewrapper.h \
		graphics/image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagewrapper.o graphics/imagewrapper.cpp

renderedimage.o: graphics/renderedimage.cpp graphics/renderedimage.h \
		graphics/imagewrapper.h \
		graphics/image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o renderedimage.o graphics/renderedimage.cpp

plottedimage.o: graphics/plottedimage.cpp graphics/plottedimage.h \
		graphics/imagewrapper.h \
		graphics/image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plottedimage.o graphics/plottedimage.cpp

selectablewidget.o: ui/selectablewidget.cpp ui/selectablewidget.h \
		fractals/specification.h \
		graphics/image.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o selectablewidget.o ui/selectablewidget.cpp

settings.o: settings.cpp settings.h \
		ui/selectablewidget.h \
		fractals/specification.h \
		graphics/image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

mainwindow.o: ui/mainwindow.cpp ui/mainwindow.h \
		fractals/specification.h \
		graphics/image.h \
		ui/imagecontrolwidget.h \
		ui/selectablewidget.h \
		settings.h \
		fractals/mandelbrot.h \
		fractals/rendering.h \
		fractals/viewport.h \
		math/transformation.h \
		graphics/renderedimage.h \
		graphics/imagewrapper.h \
		graphics/colorpalette.h \
		math/spline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ui/mainwindow.cpp

complex.o: math/complex.cpp math/complex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o complex.o math/complex.cpp

image.o: graphics/image.cpp graphics/image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o image.o graphics/image.cpp

specification.o: fractals/specification.cpp fractals/specification.h \
		graphics/image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specification.o fractals/specification.cpp

viewport.o: fractals/viewport.cpp fractals/viewport.h \
		fractals/specification.h \
		graphics/image.h \
		math/transformation.h \
		settings.h \
		ui/selectablewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewport.o fractals/viewport.cpp

rendering.o: fractals/rendering.cpp fractals/rendering.h \
		fractals/viewport.h \
		fractals/specification.h \
		graphics/image.h \
		math/transformation.h \
		graphics/renderedimage.h \
		graphics/imagewrapper.h \
		settings.h \
		ui/selectablewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rendering.o fractals/rendering.cpp

mandelbrot.o: fractals/mandelbrot.cpp fractals/mandelbrot.h \
		fractals/rendering.h \
		fractals/viewport.h \
		fractals/specification.h \
		graphics/image.h \
		math/transformation.h \
		graphics/renderedimage.h \
		graphics/imagewrapper.h \
		graphics/colorpalette.h \
		math/spline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mandelbrot.o fractals/mandelbrot.cpp

imagecontrolwidget.o: ui/imagecontrolwidget.cpp ui/imagecontrolwidget.h \
		ui/selectablewidget.h \
		fractals/specification.h \
		graphics/image.h \
		settings.h \
		ui/resizedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imagecontrolwidget.o ui/imagecontrolwidget.cpp

resizedialog.o: ui/resizedialog.cpp ui/resizedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resizedialog.o ui/resizedialog.cpp

moc_selectablewidget.o: moc_selectablewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_selectablewidget.o moc_selectablewidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_specification.o: moc_specification.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_specification.o moc_specification.cpp

moc_imagecontrolwidget.o: moc_imagecontrolwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_imagecontrolwidget.o moc_imagecontrolwidget.cpp

moc_resizedialog.o: moc_resizedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_resizedialog.o moc_resizedialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

